version: 2
jobs:
  build:
    working_directory: ~/tomato-wallet-front-end  # directory where steps will run
    docker:
      - image: node:11.6.0 
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-v1
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-v1
          paths:
            - /home/circleci/.yarn
      - run:
          name: Run Tests
          command: yarn test --no-watch
